language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
addons:
  apt:
    packages: bedtools
  homebrew:
    packages: bedtools
install:
    - pip install blockify
script:
    - python -m unittest tests.test_basic
